// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUWxwHs6Q3Ei_fNeOAV8ktqqVRgngOYVI',
    appId: '1:54375527170:web:80b8dff8c3a1e01c0c881b',
    messagingSenderId: '54375527170',
    projectId: 'exim-graphics-lms',
    authDomain: 'exim-graphics-lms.firebaseapp.com',
    storageBucket: 'exim-graphics-lms.firebasestorage.app',
    measurementId: 'G-9CD61L58XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFPRSNWTpkmZDNPkg2DM0zi6IOGnpWITU',
    appId: '1:54375527170:android:fe0a88d846e7889d0c881b',
    messagingSenderId: '54375527170',
    projectId: 'exim-graphics-lms',
    storageBucket: 'exim-graphics-lms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKJXuJjNrrCtX2EaCMl0r7R7ui8WoQKA',
    appId: '1:54375527170:ios:3e19b2ea767be68f0c881b',
    messagingSenderId: '54375527170',
    projectId: 'exim-graphics-lms',
    storageBucket: 'exim-graphics-lms.firebasestorage.app',
    iosClientId: '54375527170-g6k8r5cgt41tdbfi7fofo022u5lk0aia.apps.googleusercontent.com',
    iosBundleId: 'com.shilpasena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuKJXuJjNrrCtX2EaCMl0r7R7ui8WoQKA',
    appId: '1:54375527170:ios:e7786be1814861e00c881b',
    messagingSenderId: '54375527170',
    projectId: 'exim-graphics-lms',
    storageBucket: 'exim-graphics-lms.firebasestorage.app',
    iosClientId: '54375527170-reqee77a01a7v5ejq131pkjekqlhsvkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eximGraphicsLms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUWxwHs6Q3Ei_fNeOAV8ktqqVRgngOYVI',
    appId: '1:54375527170:web:85d8bab2738c57870c881b',
    messagingSenderId: '54375527170',
    projectId: 'exim-graphics-lms',
    authDomain: 'exim-graphics-lms.firebaseapp.com',
    storageBucket: 'exim-graphics-lms.firebasestorage.app',
    measurementId: 'G-BY062C9M73',
  );
}
